name: Publish Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: niku/nwiki
          username: niku
          password: ${{ secrets.DOCKER_PASSWORD }}
